export const PROD_LIST_REQ = 'PROD_LIST_REQUEST'
export const PROD_LIST_SUC = 'PROD_LIST_SUCCESS'
export const PROD_LIST_FAIL = 'PROD_LIST_FAIL'

export const PROD_DETAILS_REQ = 'PROD_DETAILS_REQUEST'
export const PROD_DETAILS_SUC = 'PROD_DETAILS_SUCCESS'
export const PROD_DETAILS_FAIL = 'PROD_DETAILS_FAIL'

export const PROD_DELETE_REQ = 'PROD_DELETE_REQUEST'
export const PROD_DELETE_SUC = 'PROD_DELETE_SUCCESS'
export const PROD_DELETE_FAIL = 'PROD_DELETE_FAIL'

export const PROD_CREATE_REQ = 'PROD_CREATE_REQUEST'
export const PROD_CREATE_SUC = 'PROD_CREATE_SUCCESS'
export const PROD_CREATE_FAIL = 'PROD_CREATE_FAIL'
export const PROD_CREATE_RESET = 'PROD_CREATE_RESET'

export const PROD_UPDATE_REQ = 'PROD_UPDATE_REQUEST'
export const PROD_UPDATE_SUC = 'PROD_UPDATE_SUCCESS'
export const PROD_UPDATE_FAIL = 'PROD_UPDATE_FAIL'
export const PROD_UPDATE_RESET = 'PROD_UPDATE_RESET'

export const PROD_CREATE_REVIEW_REQ = 'PROD_CREATE_REVIEW_REQUEST'
export const PROD_CREATE_REVIEW_SUC = 'PROD_CREATE_REVIEW_SUCCESS'
export const PROD_CREATE_REVIEW_FAIL = 'PROD_CREATE_REVIEW_FAIL'
export const PROD_CREATE_REVIEW_RESET = 'PROD_CREATE_REVIEW_RESET'

export const PROD_TOP_REQ = 'PROD_TOP_REQUEST'
export const PROD_TOP_SUC = 'PROD_TOP_SUCCESS'
export const PROD_TOP_FAIL = 'PROD_TOP_FAIL'